version: '3.9'

x-base_service: &base_service
    volumes:
      - &v1 ./models:/models
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  download:
    <<: *base_service
    container_name: download
    build: ./download/

  auto:
    <<: *base_service
    ports:
      - "7860:7860"
    build: .
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api